apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-hello-world
  labels:
    app: react-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-hello-world
  template:
    metadata:
      labels:
        app: react-hello-world
    spec:
      containers:
      - name: react-app
        image: mouhaby92/react-hello-world:1.0
        ports:
        - containerPort: 80
