apiVersion: v1
kind: Service
metadata:
  name: react-hello-world-service
spec:
  selector:
    app: react-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Or LoadBalancer if you want external access
